# Generated by Django 2.0.3 on 2018-09-02 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_applicants_comapny'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicants',
            old_name='comapny',
            new_name='company',
        ),
    ]
