# Generated by Django 2.0.3 on 2018-09-01 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first', models.CharField(blank=True, max_length=20, null=True)),
                ('last', models.CharField(blank=True, max_length=20, null=True)),
                ('regNum', models.CharField(max_length=10)),
                ('course', models.CharField(choices=[('BTech', 'B.Tech'), ('MTech', 'M.Tech'), ('MCA', 'MCA'), ('MBA', 'MBA'), ('PHD', 'Phd')], default='BTech', max_length=20)),
                ('branch', models.CharField(choices=[('-', '---SELECT---'), ('CSE', 'Computer Science & Engineering'), ('ECE', 'Electronics and Communication Engineering'), ('MECH', 'Mechanical Engineering'), ('MME', 'Metallurgy Engineering'), ('CHE', 'Chemical Engineering'), ('CIVIL', 'Civil Engineering'), ('EEE', 'Electrical and Electronics Engineering'), ('BIO', 'Biotechnology')], max_length=20)),
                ('contact', models.CharField(max_length=20)),
                ('cgpa', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('isPlaced', models.BooleanField(default=False)),
            ],
        ),
    ]
