# Generated by Django 2.0.3 on 2018-09-02 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profilePic',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
